### ISSUE TITLE
Error: Object.Keys called on non-object

### ISSUE THREAD

**Issue by mohsinjaved** [substack/webworkify#10]
I just installed this package and trying to run the provided example but getting error :

var cache = Object.keys(cache);

am I missing any dependency or anything else ?

**Comment by kumavis** [comment]
looks like `cache` is undefined.
you might be shadowing it by having `var cache` in the block

**Comment by smith-kyle** [comment]
`cache` is undefined for me as well

**Comment by GuillaumeLeclerc** [comment]
Same here, any plan on fixing this ?

**Comment by hanfeisun** [comment]
Same for me

**Comment by hanfeisun** [comment]
Same for me

**Comment by lusilva** [comment]
Any progress on this? I'm having the same issue

**Comment by canastro** [comment]
Same for me

**Comment by mrtone** [comment]
`npm i webworkify-webpack`
```js
resolve: {
    alias: {
        webworkify: 'webworkify-webpack'
    }
}

**Comment by mourner** [comment]
This is not a webworkify issue (since it is specifically created for browserify), and @mrtone provided the correct workaround. 

I think we could throw an error about not using `browserify` when you're not using it.

**Comment by aakilfernandes** [comment]
@mourner can you link @MrTONE workaround?

**Comment by mourner** [comment]
@aakilfernandes hmm, it was 3 years ago so I don't remember what I referred to unfortunately :( Maybe there was a comment here but it got deleted? Or that user renamed themselves and it's actually https://github.com/browserify/webworkify/issues/10#issuecomment-231289513 ? Not sure.

**Comment by aakilfernandes** [comment]
@mourner no worries. Thanks
