### ISSUE TITLE
Cross origin request error

### ISSUE THREAD

**Issue by tnrich** [substack/webworkify#11]
Hey there, I'm converting a web-worker to use webworkify in order to reuse a bunch of common modules. However, I'm hitting a Cross origin error when trying to post to the back-end:

XMLHttpRequest cannot load . Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

I'm not sure why I'm getting this error exactly, because I'm using the same ajax module as before. I suspect it might have something to do from it getting called from the browserify blob. Has anyone else run into this sort of issue? Any suggestions for resolving it would be appreciated.

Thanks!

**Comment by kumavis** [comment]
Hmm I guess your web worker is on a blob protocol and not a data protocol. You could try these:
* if you control the backend, just add CORS headers
* if you dont, you could run your own CORS proxy or use a public one (security concerns here)
* try moving the worker to a data uri instead of a blob uri
* you could do all the xhr from the main context. forward requests could be manually wired via `window.postMessage` or done via an rpc such as https://github.com/maxogden/workerstream and https://github.com/substack/dnode

**Comment by tnrich** [comment]
Hmm option 1 sounds easiest since we do control the backend. Do you know how to add CORS headers for a blob protocol? It seems like webworkify dynamically creates a new (semi-random) blob URL every time a new worker is requested so the CORS headers would have to use a regex.. Maybe this isn't the case though? 

Option 3 sounds interesting as well. Could you give more info on how to move the worker to a data uri? I believe this is the code where the URI is created currently:
```
    return new Worker(URL.createObjectURL(
        new Blob([src], { type: 'text/javascript' })
    ));
```
How do we use a data uri and still reference the blob object?

Thanks for your quick response! Much appreciated!

**Comment by kumavis** [comment]
you add the CORS to the response, not the request -- so not related to the protocol

something like this
https://github.com/expressjs/cors

**Comment by kumavis** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by tnrich** [comment]
Hey, so we figured out what was going on. It turns out that the ajax library we were using was automatically using the url from the blob scope. 

So when we said:
```
    request
              .post('/sequences')
              .send(parsedResult.parsedSequence)
              .set('Accept', 'application/json')
```

It was prepending blob:http%3A//localhost%3A3000 to the front of /sequences
Thus it thought we were trying to access the "blob" domain.

Once we changed the code inside the worker to use "location.origin", things started working again:
```
    request
              .post(location.origin + '/sequences')
              .send(parsedResult.parsedSequence)
              .set('Accept', 'application/json')
```

It appears that location.origin is the domain that the worker is instantiated from. 

Thanks for the help and hopefully this helps anyone else who is having similar issues.

**Comment by kumavis** [comment]
nice
`.post('//sequences')` may also work

**Comment by kumavis** [comment]
remember to close this issue -- others can still find it if they search this repo for 'cors'

**Comment by tnrich** [comment]
Cool I'll try out ```.post('//sequences')``` 
Thanks for the help!
