### ISSUE TITLE
Generated worker blob includes main dependency graph

### ISSUE THREAD

**Issue by timkurvers** [substack/webworkify#12]
The sample main/worker setup from the README includes `webworkify` in the worker blob, even though it's not required from the worker.

In the application I'm currently working on this results in a blob of approximately 1.1MB, for the following worker, due to the sheer size of the rest of the bundle:

```javascript
module.exports = function(self) {
  console.log('hello world!');
};
```

The culprit seems to be [usage of `Object.keys(sources)`](https://github.com/substack/webworkify/blob/master/index.js#L41) which will include all sources up to that point.

Is this by design?

**Comment by kumavis** [comment]
I had this problem and ended up writing https://github.com/kumavis/meowserify
however, its not very good, could be improved greatly.

**Comment by kumavis** [comment]
@timkurvers ever come up with a clever solution here?

**Comment by timkurvers** [comment]
@kumavis Not really unfortunately. I ended up [building a separate worker-bundle](https://github.com/timkurvers/wowser/commit/f05649546c0e5752f5a817a81455b02bb8d659cc) using browserify.

**Comment by mourner** [comment]
Check out #30 for a solution.
