### ISSUE TITLE
Can this work with ES6 modules?

### ISSUE THREAD

**Issue by trusktr** [substack/webworkify#15]
F.e. instead of 

```js
var w = work(require('foo'))
```

doing

```js
import foo from 'foo'
var w = work(foo)
```

? Or something?

**Comment by quarterto** [comment]
Browserify doesn't support ES2015 modules directly, but you can use an ES2015 transform like [babelify](https://github.com/babel/babelify) (with `babel-preset-es2015`).

**Comment by garthenweb** [comment]
For me it was working until I upgraded to Babel v6. See #17 for more information and a possible solution.
