### ISSUE TITLE
Cross Browser testing and minimal mock

### ISSUE THREAD

**Issue by epiloque** [substack/webworkify#20]
Hello,

I've added browserstack tests and a simple Web Worker mock. I wanted to ask if you are interested in a PR ?

https://github.com/epiloque/socialist

Thank you,

**Comment by mourner** [comment]
@anandthakker https://github.com/juliangruber/tape-run would allow writing tests for `webworkify` without mocks — I used it in https://github.com/mapbox/workerpoolify and it works great. It uses Electron as a browser environment by default.
