### ISSUE TITLE
Yield just the Blob

### ISSUE THREAD

**Issue by anandthakker** [substack/webworkify#23]
@substack I ran into a use case where I needed the Object URL _not_ wrapped in a `Worker` (so that I could send it to an existing worker, which would then execute it with `importScripts`).  For now I just forked and made `blobify`, but the code duplication seems silly -- I could make a PR back here if you think it's worth having that as a variation here.

**Comment by substack** [comment]
That sounds good to have behind an option if it's easy to do.

**Comment by anandthakker** [comment]
Thanks
