### ISSUE TITLE
Does this work for Shared Web Workers?

### ISSUE THREAD

**Issue by brandonros** [substack/webworkify#27]
My testing would show no...

**Comment by yoshuawuyts** [comment]
Would you mind sharing your testing? - What'd you run?

**Comment by toddself** [comment]
I actually just forked this and added a switch for creating a new `SharedWorker`.  I'm in the midst of writing some tests to prove it, but i've got a shared worker instance back from the call to `work` so far...

![image](https://cloud.githubusercontent.com/assets/193412/15942785/d9110916-2e3a-11e6-9033-0a78fa2ba39a.png)

**Comment by brandonros** [comment]
@toddself I wasn't able to debug it or get it to work, then I realized near 0 browsers support it.

**Comment by toddself** [comment]
Chrome and Firefox have full support. 

Although a service worker might make more sense tbh

**Comment by mourner** [comment]
If you do `webworkify(fn, {bare: true})`, it returns a bare blob instead of a Worker instance, so you can in theory create any kind of worker with it.
