### ISSUE TITLE
Webworkify + Uglify-js + Require.js not getting along 

### ISSUE THREAD

**Issue by etpinard** [substack/webworkify#29]
Hi, I'm trying to load up a browserify `--standalone` bundle that includes `webworkify` that been minified with [`uglifyjs`](https://github.com/mishoo/UglifyJS2) using the `--mangle` and `--compress` options in Require.js.

### Problem

Require.js fails to load the bundle:

![image](https://cloud.githubusercontent.com/assets/6675409/17721813/11201b62-63fb-11e6-8018-19c6581c6cb0.png)

### Reproducible example

See https://gist.github.com/etpinard/8ec2c29210d5adee049d54bb427bbbe6

### Observations

This [line](https://github.com/substack/webworkify/blob/aa591d74805f6cbe0ab2734e2ff7878184cac550/index.js#L43) seems to be causing the issue when compressed by `uglifyjs`

Replacing 

```js
'var f = require(' + stringify(wkey) + ');' +
'(f.default ? f.default : f)(self);'
```

by 

```js
'var f = require('+stringify(wkey)+');' +
'(f.default ? f.default : f)(self);'
```

and running browserify and uglifyjs without the `--compress` option is enough to replicate the problem listed above.

**Comment by mourner** [comment]
I'm really puzzled by this. Why would adding spaces around `+` sings in webworkify code affect things in any way?

**Comment by etpinard** [comment]
This one is definitively strange. It may be a bug with Require.js itself?

**Comment by mourner** [comment]
@etpinard would you mind checking if the same thing happens in https://github.com/substack/webworkify/pull/31? Just in case.

**Comment by etpinard** [comment]
I get the same Require.js error using off `mourner:no-eval` .

**Comment by etpinard** [comment]
This commit https://github.com/substack/webworkify/commit/31c27effcdc2db8378ab3b3e3fcdab649b912197 appear to fix this issue.

**Comment by mourner** [comment]
@etpinard but why?

**Comment by mourner** [comment]
Since this seems like a require+uglify bug, should we close this issue and wait for upstream fixes?

**Comment by etpinard** [comment]
> Since this seems like a require+uglify bug

I believe this is a Require.js bug, but I haven't had the time to investigate further.

For our needs, I was able to fix this issue using a dirty string `.replace` [here](https://github.com/plotly/plotly.js/blob/master/tasks/util/patch_minified.js) and test it [here](https://github.com/plotly/plotly.js/blob/master/test/jasmine/bundle_tests/requirejs_test.js). So you can close this issue if you like. 

Thanks for your time.
