### ISSUE TITLE
Can't shake the URL call

### ISSUE THREAD

**Issue by kevincolten** [substack/webworkify#33]
Though this is working, I can't seem to shake this request error. Am I missing something?

![screen shot 2016-11-09 at 5 36 26 pm](https://cloud.githubusercontent.com/assets/4411115/20158961/5b12565a-a6a3-11e6-8865-22a9bf7431c1.png)

Here's my code

```js
var work = require('webworkify');
var worker = work(require('worker.sql.js'));

worker.onmessage = function() {
  URL.revokeObjectURL(worker.objectURL);
  console.log("Database opened");
  worker.onmessage = function(event){
    console.log(event.data); // The result of the query
  };
}
worker.onerror = function(e) {console.log("Worker error: ", e)};
worker.postMessage({
  id: 1,
  action: 'open',
  buffer: new Uint8Array(this.response),
});
```

**Comment by mourner** [comment]
Can you post the code from `worker.sql.js`, or set up a minimal test case?

**Comment by kevincolten** [comment]
Sadly, it's [compiled](https://github.com/kripken/sql.js/blob/master/js/worker.sql.js) but after [trying it](https://github.com/kripken/sql.js/#use-as-web-worker) with a few different web worker libraries, it seems to happen with all of them. So it must be something going on in the script. I'll submit an issue there.

**Comment by kevincolten** [comment]
Actually, it looks more like a compiling issue

![screen shot 2016-11-10 at 8 50 18 am](https://cloud.githubusercontent.com/assets/4411115/20181196/d178ea82-a722-11e6-95e3-ddfeb9e6ab5f.png)

**Comment by mourner** [comment]
@kevincolten what if you replace the big compiled script with a minimal one enough to reproduce this?
