### ISSUE TITLE
Dynamic require() in the worker

### ISSUE THREAD

**Issue by snajjar** [substack/webworkify#34]
Hello,

I'm trying to resolve dynamically modules that are included in the bundle.

The worker works fine when i'm doing some basic require:
`var m = require('my-module');`

But if i want to resolve a module dynamically:
`
var a = 'my-module';
var m = require(a);
`

It issues a "MODULE_NOT_FOUND" error, even though the module is defined in the bundle (with working require() calls). How can i make dynamic require() with webworkify?

Notes: I'm trying to setup a pool of workers to accomplish specific tasks on demand (and there's a LOT of tasks), that's why i need to be able to dynamically require the appropriate module when receiving a specific task.

**Comment by mourner** [comment]
This is technically not possible with webworkify currently. However, you should check out my attempt at solving exactly this problem with a new module — https://github.com/mapbox/workerpoolify
