### ISSUE TITLE
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not a function

### ISSUE THREAD

**Issue by sallyamoore** [substack/webworkify#36]
Likely due to a missing semicolon.

**Comment by mourner** [comment]
Looks like the same issue was reported before — #33 — but got closed because there was no reproducible test case... Can you try setting it up? Bonus points if you can PR a fix of course :)

**Comment by sallyamoore** [comment]
Yep, I can verify that I've got the same error. I'll work on setting up a test case. 


![screen shot 2017-06-16 at 9 07 25 am](https://user-images.githubusercontent.com/10969102/27234863-6dfd28c2-5273-11e7-87cc-84543b341108.png)

**Comment by sallyamoore** [comment]
I'm pretty certain that the problem is here: 
![screen shot 2017-06-16 at 9 22 33 am](https://user-images.githubusercontent.com/10969102/27235402-9163271a-5275-11e7-8c63-a1a2e35789cf.png)

On line 44 in `index.js`, there's a missing semicolon between `(f.default ? f.default : f)` and `(self);`. If I run the compiled code in the console without that semicolon, I see the error. If I add it, the error disappears. Here's the code I'm running (with the semicolon added):

```javascript 
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"67":[function (require,module,exports){
"use strict";

onmessage = function onmessage(e) {
	if (e && e.data && e.data.event === "TEST") {
		var toRun = eval(e.data.method);
		toRun(e.data.params);
	}
};
onerror = function onerror(e) {
	console.log(e);
};

},{}],"b6813867":[function anonymous(require
/*``*/) {
var f = require("67");(f.default ? f.default : f);(self);
},{"67":"67"}]},{},["b6813867"])
```
Is this enough info? It's not really a full test case, but it reproduces the error and demonstrates how to solve it. I'm happy to make a quick PR if that's helpful! Thanks!

**Comment by anandthakker** [comment]
There isn't (and shouldn't be) a semicolon between (f.default ? f.default : f)(self), because this is intended to be a function call -- `(f.default ? f.default : f)` refers to the function exported by the module being webworkified, and `self` is the single argument to that function.

@sallyamoore is it possible that the module on which you're calling webworkify does not export a function (i.e. `module.exports = function (self) {...}`)?

**Comment by sallyamoore** [comment]
Ah yes, I was exporting multiple functions from the module, which I now see is not what webworkify is expecting. When I nested those functions within `function(self) {...}`, the error disappeared and the worker functioned as expected. Thanks for your help (and patience)!
