### ISSUE TITLE
Can't set breakpoint in webworker

### ISSUE THREAD

**Issue by doxxx** [substack/webworkify#9]
I'm using browserify and webworkify with sourcemaps but any breakpoint I set in the sourcemap'd file in Chrome is not hit.

My gulpfile task looks like this:

```javascript
gulp.task('processjs', function () {
  var b = browserify({
    entries: 'app/js/app.js',
    debug: true,
    transform: [cacheify(babelify, babelifyCache), cacheify(ngAnnotate, ngAnnotateCache)]
  });

  return b.bundle()
    .on('error', errorHandler)
    .pipe(source('all.js'))
    .pipe(buffer())
    .pipe(sourcemaps.init({loadMaps: true}))
    // post-browserify transform tasks go here
    .pipe(uglify())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('dist'));
});
```

**Comment by kumavis** [comment]
are you sure your transforms are not the problem?

**Comment by doxxx** [comment]
I have no idea, I'm kinda new to this.

However, when an error occur in the webworkified worker, the stopping point in the Chrome debugger is in an embedded data URI. I.e. the source of the worker has been converted into a data URI. So, it's not actually executing the source that was transformed by browserify, which would have sourcemap annotations.

**Comment by doxxx** [comment]
Also, I can set breakpoints in other code which was processed by the same set of transforms.

**Comment by kumavis** [comment]
in the mean time you can use `debugger`

**Comment by doxxx** [comment]
Could you elaborate a little on what you mean by `debugger`?

**Comment by kumavis** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger

**Comment by doxxx** [comment]
I see, thanks.

**Comment by tnrich** [comment]
Also running into this issue. The debugger statement does work, but it would be nice to be able to set breakpoints as well. Anyone had any luck getting breakpoints to work?

**Comment by mourner** [comment]
This is something that's not possible to fix because worker sources are created dynamically (with blob URLs), so breakpoints you set on a generated source don't persist after reloading a page.

`debugger` statements are a simple and effective workaround, so I'm closing the issue as not actionable.

**Comment by jfirebaugh** [comment]
See also http://stackoverflow.com/a/24198720/52207
